# Generated by Django 6.0.3 on 2026-04-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filtros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto', models.CharField(blank=True, max_length=255, null=True)),
                ('processo', models.CharField(blank=True, max_length=100, null=True)),
                ('orgao', models.CharField(blank=True, max_length=255, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('municipio', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('modalidade', models.CharField(blank=True, max_length=100, null=True)),
                ('realizacao', models.CharField(blank=True, max_length=100, null=True)),
                ('julgamento', models.CharField(blank=True, max_length=100, null=True)),
                ('periodo_inicio', models.DateField(blank=True, null=True)),
                ('periodo_fim', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
