# Generated by Django 6.0.3 on 2026-04-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiltroOpcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(choices=[('status', 'Status'), ('realizacao', 'Realizacao'), ('modalidade', 'Modalidade'), ('julgamento', 'Julgamento')], max_length=30)),
                ('valor', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['campo', 'valor'],
                'unique_together': {('campo', 'valor')},
            },
        ),
    ]
