# Generated by Django 6.0.3 on 2026-04-03 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filtros', '0003_filtros_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filtroopcao',
            options={'ordering': ['campo', 'valor'], 'verbose_name': 'Opção de Filtro', 'verbose_name_plural': 'Opções de Filtro'},
        ),
        migrations.AlterModelOptions(
            name='filtros',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Filtro', 'verbose_name_plural': 'Filtros'},
        ),
    ]
